# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_xPyPot', [dirname(__file__)])
        except ImportError:
            import _xPyPot
            return _xPyPot
        if fp is not None:
            try:
                _mod = imp.load_module('_xPyPot', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _xPyPot = swig_import_helper()
    del swig_import_helper
else:
    import _xPyPot
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Modified(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Modified, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Modified, name)
    __repr__ = _swig_repr
    MOD_SELF = _xPyPot.Modified_MOD_SELF
    MOD_SIMULATION = _xPyPot.Modified_MOD_SIMULATION
    def __init__(self, *args, **kwargs): 
        this = _xPyPot.new_Modified(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    def set(self, *args, **kwargs): return _xPyPot.Modified_set(self, *args, **kwargs)
    def clear(self, *args, **kwargs): return _xPyPot.Modified_clear(self, *args, **kwargs)
    def update(self, *args, **kwargs): return _xPyPot.Modified_update(self, *args, **kwargs)
    def value(self, *args, **kwargs): return _xPyPot.Modified_value(self, *args, **kwargs)
    def __call__(self, *args, **kwargs): return _xPyPot.Modified___call__(self, *args, **kwargs)
    __swig_destroy__ = _xPyPot.delete_Modified
    __del__ = lambda self : None;

class ModifiedPtr(Modified):
    def __init__(self, this):
        try: self.this.append(this)
        except: self.this = this
        self.this.own(0)
        self.__class__ = Modified

Modified_swigregister = _xPyPot.Modified_swigregister
Modified_swigregister(Modified)

class ModifiedBase(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModifiedBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ModifiedBase, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["modified"] = _xPyPot.ModifiedBase_modified_set
    __swig_getmethods__["modified"] = _xPyPot.ModifiedBase_modified_get
    if _newclass:modified = _swig_property(_xPyPot.ModifiedBase_modified_get, _xPyPot.ModifiedBase_modified_set)
    __swig_setmethods__["registeredSimulations"] = _xPyPot.ModifiedBase_registeredSimulations_set
    __swig_getmethods__["registeredSimulations"] = _xPyPot.ModifiedBase_registeredSimulations_get
    if _newclass:registeredSimulations = _swig_property(_xPyPot.ModifiedBase_registeredSimulations_get, _xPyPot.ModifiedBase_registeredSimulations_set)
    __swig_destroy__ = _xPyPot.delete_ModifiedBase
    __del__ = lambda self : None;
    def registerTo(self, *args, **kwargs): return _xPyPot.ModifiedBase_registerTo(self, *args, **kwargs)
    def unRegister(self, *args, **kwargs): return _xPyPot.ModifiedBase_unRegister(self, *args, **kwargs)
    def updateValues(self, *args, **kwargs): return _xPyPot.ModifiedBase_updateValues(self, *args, **kwargs)

class ModifiedBasePtr(ModifiedBase):
    def __init__(self, this):
        try: self.this.append(this)
        except: self.this = this
        self.this.own(0)
        self.__class__ = ModifiedBase

ModifiedBase_swigregister = _xPyPot.ModifiedBase_swigregister
ModifiedBase_swigregister(ModifiedBase)

class PyPot(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyPot, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PyPot, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _xPyPot.new_PyPot(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self, *args, **kwargs): return _xPyPot.PyPot___deref__(self, *args, **kwargs)
    def __ref__(self, *args, **kwargs): return _xPyPot.PyPot___ref__(self, *args, **kwargs)
    def registerInstanceData(self, *args, **kwargs): return _xPyPot.PyPot_registerInstanceData(self, *args, **kwargs)
    def decrRefCnt(self, *args, **kwargs): return _xPyPot.PyPot_decrRefCnt(self, *args, **kwargs)
    def incrRefCnt(self, *args, **kwargs): return _xPyPot.PyPot_incrRefCnt(self, *args, **kwargs)
    def refCnt(self, *args, **kwargs): return _xPyPot.PyPot_refCnt(self, *args, **kwargs)
    def instanceData(self, *args, **kwargs): return _xPyPot.PyPot_instanceData(self, *args, **kwargs)
    def help(self, *args, **kwargs): return _xPyPot.PyPot_help(self, *args, **kwargs)
    __oldinit__=__init__
    def __init__(self, *args):
        self.__oldinit__(*args)
        self.registerInstanceData(self)

    __swig_destroy__ = _xPyPot.delete_PyPot
    __del__ = lambda self : None;
    def rms(self, *args, **kwargs): return _xPyPot.PyPot_rms(self, *args, **kwargs)
    def violations(self, *args, **kwargs): return _xPyPot.PyPot_violations(self, *args, **kwargs)
    def numRestraints(self, *args, **kwargs): return _xPyPot.PyPot_numRestraints(self, *args, **kwargs)
    def pythonPot(self, *args, **kwargs): return _xPyPot.PyPot_pythonPot(self, *args, **kwargs)
    def simulation(self, *args, **kwargs): return _xPyPot.PyPot_simulation(self, *args, **kwargs)
    def help(self, *args, **kwargs): return _xPyPot.PyPot_help(self, *args, **kwargs)
    def potName(self, *args, **kwargs): return _xPyPot.PyPot_potName(self, *args, **kwargs)
    def instanceName(self, *args, **kwargs): return _xPyPot.PyPot_instanceName(self, *args, **kwargs)
    def resetPotName(self, *args, **kwargs): return _xPyPot.PyPot_resetPotName(self, *args, **kwargs)
    def scale(self, *args, **kwargs): return _xPyPot.PyPot_scale(self, *args, **kwargs)
    def setScale(self, *args, **kwargs): return _xPyPot.PyPot_setScale(self, *args, **kwargs)
    def threshold(self, *args, **kwargs): return _xPyPot.PyPot_threshold(self, *args, **kwargs)
    def setThreshold(self, *args, **kwargs): return _xPyPot.PyPot_setThreshold(self, *args, **kwargs)
    def calcEnergy(self, *args, **kwargs): return _xPyPot.PyPot_calcEnergy(self, *args, **kwargs)
    def calcEnergyAndDerivs(self, *args, **kwargs): return _xPyPot.PyPot_calcEnergyAndDerivs(self, *args, **kwargs)
    def updateValues(self, *args, **kwargs): return _xPyPot.PyPot_updateValues(self, *args, **kwargs)
    def updateDelta(self, *args, **kwargs): return _xPyPot.PyPot_updateDelta(self, *args, **kwargs)
    __swig_setmethods__["instanceData_"] = _xPyPot.PyPot_instanceData__set
    __swig_getmethods__["instanceData_"] = _xPyPot.PyPot_instanceData__get
    if _newclass:instanceData_ = _swig_property(_xPyPot.PyPot_instanceData__get, _xPyPot.PyPot_instanceData__set)
    __swig_setmethods__["instanceDataCreate"] = _xPyPot.PyPot_instanceDataCreate_set
    __swig_getmethods__["instanceDataCreate"] = _xPyPot.PyPot_instanceDataCreate_get
    if _newclass:instanceDataCreate = _swig_property(_xPyPot.PyPot_instanceDataCreate_get, _xPyPot.PyPot_instanceDataCreate_set)
    __swig_setmethods__["instanceDataCleanup"] = _xPyPot.PyPot_instanceDataCleanup_set
    __swig_getmethods__["instanceDataCleanup"] = _xPyPot.PyPot_instanceDataCleanup_get
    if _newclass:instanceDataCleanup = _swig_property(_xPyPot.PyPot_instanceDataCleanup_get, _xPyPot.PyPot_instanceDataCleanup_set)
    __swig_setmethods__["modified"] = _xPyPot.PyPot_modified_set
    __swig_getmethods__["modified"] = _xPyPot.PyPot_modified_get
    if _newclass:modified = _swig_property(_xPyPot.PyPot_modified_get, _xPyPot.PyPot_modified_set)
    __swig_setmethods__["registeredSimulations"] = _xPyPot.PyPot_registeredSimulations_set
    __swig_getmethods__["registeredSimulations"] = _xPyPot.PyPot_registeredSimulations_get
    if _newclass:registeredSimulations = _swig_property(_xPyPot.PyPot_registeredSimulations_get, _xPyPot.PyPot_registeredSimulations_set)
    def registerTo(self, *args, **kwargs): return _xPyPot.PyPot_registerTo(self, *args, **kwargs)
    def unRegister(self, *args, **kwargs): return _xPyPot.PyPot_unRegister(self, *args, **kwargs)

class PyPotPtr(PyPot):
    def __init__(self, this):
        try: self.this.append(this)
        except: self.this = this
        self.this.own(0)
        self.__class__ = PyPot

PyPot_swigregister = _xPyPot.PyPot_swigregister
PyPot_swigregister(PyPot)

realPyPot = PyPot
def PyPot(*args):
    from potProxy import PotProxy
    return PotProxy( realPyPot(*args) )
#this next bit may be specific to a swig version (works w/ 1.3.40)
realPyPot.__setattr__ = lambda self, name, value: _swig_setattr(self, realPyPot, name, value)
realPyPot.__getattr__ = lambda self, name: _swig_getattr(self, realPyPot, name)

PyPot = realPyPot #PyPot will never be created stand-alone,
                  #so it doesn't need to be PotProxy-wrapped.
		  #However, user-created Pots w/swig-wrapped components
		  #will have to be explicitly wrapped.
oldConstructor = PyPot.__init__
def construct(self, *args):
    if len(args)==1:
        args = list(args)
	args.append(self)
    oldConstructor(self,*args)
    _swig_setattr(self, PyPot, 'thisown', 1)
PyPot.__init__ = construct

import derivList

class PyPot_LetterClass(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PyPot_LetterClass, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PyPot_LetterClass, name)
    __repr__ = _swig_repr
    def __init__(self, *args, **kwargs): 
        this = _xPyPot.new_PyPot_LetterClass(*args, **kwargs)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xPyPot.delete_PyPot_LetterClass
    __del__ = lambda self : None;
    def rms(self, *args, **kwargs): return _xPyPot.PyPot_LetterClass_rms(self, *args, **kwargs)
    def violations(self, *args, **kwargs): return _xPyPot.PyPot_LetterClass_violations(self, *args, **kwargs)
    def numRestraints(self, *args, **kwargs): return _xPyPot.PyPot_LetterClass_numRestraints(self, *args, **kwargs)
    def pythonPot(self, *args, **kwargs): return _xPyPot.PyPot_LetterClass_pythonPot(self, *args, **kwargs)
    def simulation(self, *args, **kwargs): return _xPyPot.PyPot_LetterClass_simulation(self, *args, **kwargs)
    def help(self, *args, **kwargs): return _xPyPot.PyPot_LetterClass_help(self, *args, **kwargs)

class PyPot_LetterClassPtr(PyPot_LetterClass):
    def __init__(self, this):
        try: self.this.append(this)
        except: self.this = this
        self.this.own(0)
        self.__class__ = PyPot_LetterClass

PyPot_LetterClass_swigregister = _xPyPot.PyPot_LetterClass_swigregister
PyPot_LetterClass_swigregister(PyPot_LetterClass)


def fromPy(*args, **kwargs):
  return _xPyPot.fromPy(*args, **kwargs)
fromPy = _xPyPot.fromPy
pyXplorHelp = help


def help(*args):
  return _xPyPot.help(*args)
help = _xPyPot.help
# This file is compatible with both classic and new-style classes.


